// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sojyzxpkxsmbbtmyqyvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvanl6eHBreHNtYmJ0bXlxeXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTg2ODksImV4cCI6MjA1NTk5NDY4OX0.GOLAMVRpg_vVDqwJb0jFuvzQDmfmnk0TZMoBQ6AHZVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);